name: Build and Test
on: [push]
jobs:
  framework-arduino:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: esphome/build-action@v1.5.2
      id: esphome-build
      with:
        yaml_file: .github/conf_arduino.yml
  
  framework-espidf:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: esphome/build-action@v1.5.2
      id: esphome-build
      with:
        yaml_file: .github/conf_esp_idf.yml