name: Build and Test
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'example.yaml'
      - 'nasa.md'
      - 'security.md'
      - 'LICENSE'
      - 'CONTRIBUTING.md'
      - 'docs/model-checker/**'
      - '.github/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'example.yaml'
      - 'nasa.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - 'CONTRIBUTING.md'
      - 'docs/model-checker/**'
      - '.github/**'
      
jobs:
  framework-arduino:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v3
    - uses: esphome/build-action@v3.1.0
      id: esphome-build
      with:
        yaml_file: .github/conf_arduino.yml
  
  framework-espidf:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v3
    - name: Install ESP-IDF v5.3.2
      run: |
        git clone -b v5.3.2 --recursive https://github.com/espressif/esp-idf.git esp-idf-v5.3.2
        export IDF_PATH=$PWD/esp-idf-v5.3.2
        ./esp-idf-v5.3.2/install.sh
        . ./esp-idf-v5.3.2/export.sh
    - uses: esphome/build-action@v3.1.0
      id: esphome-build
      with:
        yaml_file: .github/conf_esp_idf.yml

  #tests:
  #  runs-on: ubuntu-latest     
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: install cpp
  #    run: sudo apt-get install -y build-essential
  #  - name: chmod
  #    run: sudo chmod +x test/*.sh
  #  - name: runtest
  #    run: sudo test/test.sh
      
